app:
    resource: "@AppBundle/Controller/"
    type:     annotation
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /job
        permanent: true
app_job:
    resource: "@AppBundle/Resources/config/routing/job.yml"
    prefix: /job
