AppBundle\Entity\job:
    type: entity
    table: job
    repositoryClass: AppBundle\Repository\jobRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: 255
            nullable: true
        company:
            type: string
            length: 255
        logo:
            type: string
            length: 255
            nullable: true
        url:
            type: string
            length: 255
            nullable: true
        position:
            type: string
            length: 255
        location:
            type: string
            length: 255
        description:
            type: text
        howToApply:
            type: text
            column: how_to_apply
        token:
            type: string
            length: 255
            unique: true
        isPublic:
            type: boolean
            nullable: true
            column: is_public
        isActivated:
            type: boolean
            nullable: true
            column: is_activated
        email:
            type: string
            length: 255
        expiresAt:
            type: datetime
            column: expires_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    manyToOne:
        category:
         targetEntity: Category
         inversedBy: jobs
         joinColumn:
          name: category_id
          referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]
